sudo: required
services:
  - docker

before_install:
  - docker build -t armoured/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run armoured/react-test npm test -- --coverage

after_success:
  - docker build -t armoured/multi-client ./client
  - docker build -t armoured/multi-nginx ./nginx
  - docker build -t armoured/multi-server ./server
  - docker build -t armoured/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push armoured/multi-client
  - docker push armoured/multi-nginx
  - docker push armoured/multi-server
  - docker push armoured/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-719550164414
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
